export const START_GET_CHARACTERS = 'START_GET_CHARACTERS';
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
