export const START_GET_CHARACTERS = 'START_GET_CHARACTERS';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';

export const START_GET_QUOTE = 'START_GET_QUOTE'
export const QUOTE_SUCCESS = 'QUOTE_SUCESS';
export const QUOTE_ERROR = 'QUOTE_ERROR'
